### ISSUE TITLE
Add feature to scraper to store new info to the DB

### ISSUE THREAD

**Issue by lnros** [lnros/real-estate-web-scraping#12]

**Comment by lnros** [comment]
Handle the cases for both scrapers. Maybe merge different parking spot options into only one and street_name and house_number into address

**Comment by Shahar9772** [comment]
Done

**Comment by lnros** [comment]
Pass each new property to the properties table, each new property type to the property_types table, each new city to cities table. Handle when the information is not new.
listings table: listying_type = {buy, rent, commercial, new_home}
